wandb_version: 1

activation_funcs:
  desc: null
  value: Tanh
lr:
  desc: null
  value: 0.0003
num_nodes:
  desc: null
  value: 128
optimizer_choices:
  desc: null
  value: RMSProp
_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.15.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1683498932.020259
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 23
      - 37
      4: 3.11.3
      5: 0.15.2
      8:
      - 3
      - 5
